<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="exo_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="stand_mass" value="0.550" /> <!-- arbitrary value for mass -->
  <xacro:property name="shoulder_mass" value="0.089" />
  <xacro:property name="upperarm_mass" value="0.211" />
  <xacro:property name="forearm_mass" value="0.165" />
  <xacro:property name="stand_length" value="0.6" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="shoulder_length" value="0.165" />
  <xacro:property name="upperarm_length" value="0.3" />
  <xacro:property name="forearm_length" value="0.285" />
  <xacro:property name="width" value="0.015" />
  <!-- <xacro:property name="camera_link" value="0.05" /> Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.0075" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find exo_arm)/urdf/exo_arm.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find exo_arm)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="stand"/>
  </joint>

  <!-- Base Link -->
  <link name="stand">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/stand.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/stand.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${stand_mass}"/>
      <inertia
	  ixx="0.0165" ixy="0.0" ixz="0.0"
	  iyy="0.0165" iyz="0.0"
	  izz="0.00008"/>
    </inertial>
  </link>

  <joint name="joint1" type="fixed">
    <parent link="stand"/>
    <child link="shoulder"/>
    <origin xyz="0 ${2*width} ${stand_length - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- <dynamics damping="0.7"/> -->
  </joint>

  <!-- Middle Link -->
  <link name="shoulder">
    <collision>
      <origin xyz="0 0 -0.015" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/shoulder.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -0.015" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/shoulder.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 -0.015" rpy="1.57 0 0"/>
      <mass value="${shoulder_mass}"/>
      <inertia
	  ixx="0.000016" ixy="0.0"      ixz="0.0"
	  iyx="0.0"      iyy="0.000247" iyz="0.0"
	  izx="0.0"      izy="0.0"      izz="0.000245"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="shoulder"/>
    <child link="upperarm"/>
    <origin xyz="${shoulder_length} -0.026 0" rpy="0 0 1.57"/>
    <axis xyz="0 1 0"/>
    <!-- <dynamics damping="0.7"/> -->
  </joint> 

  <!-- Top Link -->
  <link name="upperarm">
    <collision>
      <origin xyz="${upperarm_length - 0.01} 0.105 -0.08" rpy="0 0 3.14"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/upperarm.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${upperarm_length - 0.01} 0.105 -0.08" rpy="0 0 3.14"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/upperarm.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${upperarm_length - 0.01} 0.105 -0.08" rpy="0 0 3.14"/>
      <mass value="${upperarm_mass}"/>
      <inertia
      ixx="0.000457" ixy="0.000025"  ixz="0.0"
      iyx="0.000025" iyy="0.00154"   iyz="0.0"
      izx="0.0"      izy="0.0"       izz="0.00172"/>
      </inertial>
  </link>

  <joint name="joint3" type="continuous">
    <parent link="upperarm"/>
    <child link="forearm"/>
    <origin xyz="${upperarm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- <dynamics damping="0.7"/> -->
  </joint> 

  <!-- Top Link -->
  <link name="forearm">
    <collision>
      <origin xyz="-0.04 0.090 -0.052" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/forearm.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.04 0.090 -0.052" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://exo_arm/meshes/forearm.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="-0.04 0.090 -0.052" rpy="1.57 0 0"/>
      <mass value="${forearm_mass}"/>
      <inertia
      ixx="0.000185"    ixy="0.000000114"   ixz="-0.000118"
      iyx="0.000000114" iyy="0.001199"      iyz="-0.000000075"
      izx="-0.000180"   izy="-0.000000075"  izz="0.001114"/>
      </inertial>
  </link>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
</robot>